server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: grpc-client

grpc:
  client:
    test:
      address: 'static://localhost:9090'
      negotiation-type: PLAINTEXT
